- name: Get Grafana Password
  shell: |
    kubectl -n grafana get secret grafana -o json | jq -r '.data | .["admin-password"]' | base64 -d && \
    echo && echo && echo "This is your grafana password"