- name: Create a jenkins namespace
  k8s:
    name: jenkins
    api_version: v1
    kind: Namespace
    state: present

- name: Install jenkins
  shell: |
    helm install --name jenkins \
    --namespace jenkins \
    stable/jenkins \
    -f roles/jenkins/tasks/jenkins-values.yaml

- name: Create SA and Cluster role binding
  import_tasks: jenkins-sa-role.yaml